### ISSUE TITLE
flag to add $@ automatically

### ISSUE THREAD

**Issue by zakuro9715** [zakuro9715/z#5]
```
tasks:
  echo1:
    pass_args: true
    run: echo hello
  echo2:
    run: echo hello $@
```
